---
- hosts: myServers
  tasks:
    - name: Clone app's repository into /opt.
      git:
        repo: https://github.com/daniel570/arcusteam-test.git #git@github.com:daniel570/arcusteam-test.git
        version: master
        dest: /opt/app
        accept_hostkey: yes
      become: yes
