---
- hosts: myServers
  remote_user: ubuntu
  become: True
  tasks:
    - name: Install nginx
      apt:
        name: nginx
        state: present

    - name: copy nginx config file
      copy: src=files/nginx.conf dest=/etc/nginx/nginx.conf
        #    - name: Create default index page
        #      copy:
        #        dest: /usr/share/nginx/html/index.html
        #        content: "Howdy from {{ ansible_hostname }}"
    - name: Restart nginx
      service:
        name: nginx
        state: restarted
